services:
  - type: web
    name: melanoma-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn uploads.server:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
